// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("collapse/open comment", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("collapse/open comment", async function () {
    await driver.get("https://reddit-lw.netlify.app/");
    await driver.manage().window().setRect({ width: 782, height: 919 });
    await driver
      .findElement(By.css("#\\31 2dvzhw > .MuiStack-root .MuiTypography-root"))
      .click();
    await driver
      .findElement(By.css("#cc-jf888ef .MuiCardHeader-avatar path"))
      .click();
    await driver
      .findElement(By.css("#cc-jf888ef .MuiCardHeader-avatar .MuiSvgIcon-root"))
      .click();
  });
});
